### ISSUE TITLE
jruby prompt adding chars?

### ISSUE THREAD

**Issue by mooreniemi** [jruby/jruby#2503]
in pry (using a custom prompt), i see it add up  to 4 chars. for instance, if i type "foodler", hit enter, then up arrow to retype, "food" will be caught in the prompt. if i press enter, it will clear the cursor back to the actual  prompt end. i've talked to the pry guys  and i'm not 100% sure it isn't  an issue there, but i hoped  you could help lead me to a fix.

![screenshot 2015-01-22 17 38 19](https://cloud.githubusercontent.com/assets/1695630/5866240/798c6ab8-a25d-11e4-939d-f03618a23825.png)

in vanilla irb (no custom config, nothing), i see slightly different (but maybe related?) behavior, when i hit return on an empty line, chars will be  added to the subsequent line and however many times i press enter, those extra chars will remain. if i type something in and hit enter, the cursor  will return to the proper spacing from  the prompt.

![screenshot 2015-01-22 17 29 12](https://cloud.githubusercontent.com/assets/1695630/5866189/130febf2-a25d-11e4-8448-b4f3f8d37035.png)

**Comment by DavidEGrayson** [comment]
If the JRuby verison number in your IRB screenshot is accurate, you are using a pretty old version.  I think you should try out [9.0.0.0-pre1](http://jruby.org/2015/01/20/jruby-9-0-0-0-pre1.html) to see if the problem was already fixed.

I can't reproduce the IRB problem using JRuby 9.0.0.0-pre1 in Windows.

**Comment by mooreniemi** [comment]
the pry prompt is still an issue in 1.7.10  and 1.7.13, fwiw. but the other cursor handling issue (second one) -- youre right, appears to  be resolved in 1.7.10 +.  i'll bark at  the pry  guys :)

**Comment by headius** [comment]
Pry may be expecting more out of the `readline` Ruby stdlib than we're able to provide, or else that lib under Windows has some issues. I assume this doesn't happen on non-Windows?

Also, if we are working correctly in 9k.pre1 perhaps there's something to backport, but the priority of fixing in 1.7.x is somewhat reduced in my mind.

**Comment by kyrylo** [comment]
I was able to reproduce this bug with Pry 0.10.1 (the latest version) and JRuby 9.0.0.0.pre1 on Linux, using [this prompt](https://github.com/pixelastic/sov/blob/master/issues/pry/493/pryrc).

The same version of Pry doesn't feature this bug on CRuby 2.2.0. Perhaps, because [CRuby's readline supports](https://www.ruby-forum.com/topic/213807#928426) RL_PROMPT_START_IGNORE and RL_PROMPT_END_IGNORE.
