### ISSUE TITLE
Unexpected behaviour of Process.waitpid...?

### ISSUE THREAD

**Issue by lukehorvat** [jruby/jruby#3117]
test.rb:

```ruby
pid = Process.spawn("sleep 3")
puts Process.waitpid(pid, Process::WNOHANG).nil?
sleep 6
puts Process.waitpid(pid, Process::WNOHANG).nil?
```

Executing the script above with Ruby v2.2.2 produces the following output:

```bash
true
false
```

And executing it with JRuby v1.7.20 produces this:

```bash
false
Errno::ECHILD: No child processes - No child processes
  waitpid at org/jruby/RubyProcess.java:536
  waitpid at org/jruby/RubyProcess.java:521
   (root) at test.rb:4
```

It seems `Process.waitpid` returns zero instead of `nil` while the child process hasn't exited. Is this different behaviour known/expected?

If it is, what is the best way to check that a child process is still running and has not exited yet? Simply `Process.waitpid(pid, Process::WNOHANG) == 0`?

**Comment by enebo** [comment]
Tried this on 9k also and it is a little better:

```text
false
false
```

but still broken.  So both branches have issue(s).

**Comment by headius** [comment]
I would guess that WNOHANG is not doing anything. Investigating.

**Comment by headius** [comment]
Nevermind, WNOHANG seems ok. We just weren't returning nil for a zero result from waitpid. Fixing.

**Comment by headius** [comment]
Fixed for 9k.rc2 and 1.7.22.

**Comment by lukehorvat** [comment]
@headius Thanks!

**Comment by Freaky** [comment]
I think you missed fixing `Process.waitpid2`:

    Process.waitpid2(Process.spawn("/bin/sleep", "5"), Process::WNOHANG)
    => [0, #<Process::Status: pid 0 signal 36>] 

jruby 9.0.1.0-SNAPSHOT (2.2.2) 2015-08-01 6a9fcf8 OpenJDK 64-Bit Server VM 25.51-b03 on 1.8.0_51-b16 +jit [FreeBSD-amd64]

**Comment by headius** [comment]
@Freaky Good catch! Fixed!
