### ISSUE TITLE
Warning "io/console not supported; tty will not be manipulated" occurs again on 9.0.4.0 (2.2.2) 2015-11-12

### ISSUE THREAD

**Issue by tukanos** [jruby/jruby#3700]
I'm trying to work with readline and I get this working 

```Ruby
jruby -v -rreadline -e "p Readline.readline"
```

### Environment
The versions installed:
```
--> jruby -v
jruby 9.0.4.0 (2.2.2) 2015-11-12 b9fb7aa Java HotSpot(TM) Client VM 25.66-b17 on
 1.8.0_66-b17 +jit [Windows 7-x86]
````
```
--> java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) Client VM (build 25.66-b17, mixed mode, sharing)
```
```
--> wmic OS get Caption,CSDVersion,OSArchitecture,Version
Caption                         CSDVersion      OSArchitecture  Version
Microsoft Windows 7 Enterprise  Service Pack 1  64-bit          6.1.7601
```

### Expected Behavior
To move the cursor right/left to edit output with keys right and left (gives OK output) only and not to show warning message.
```io/console not supported; tty will not be manipulated```

### Actual Behavior
Showing the message and unable to move the caret around.

**Comment by kares** [comment]
it has been fixed since 9.0.4.0 ... actually 9.0.5.0 should have the fix already.

**Comment by tukanos** [comment]
Not true.  The issue remains still at 9.0.5.0 (I have opened separate ticket at https://github.com/jruby/jruby/issues/3704).  Could you point me to the patch that should fix that?

**Comment by enebo** [comment]
@kares @tukanos The fix for 9.0.5.0 was to re-add a $VERBOSE check since this warning is only supposed to print out if verbose output is enabled.  I explained in #3704 why this warning is being seen and opened #3705 to track implementing proper io/console support on windows.
