### ISSUE TITLE
can not require openssl with JDK9

### ISSUE THREAD

**Issue by mkristian** [jruby/jruby#4805]
```
$ java --version
java 9
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```

reproduce:
```
$ java -Djruby.backtrace.style=full -jar jruby-complete-9.1.13.0.jar -ropenssl -e 1
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.io.FilenoUtil (file:/Users/christian/.m2/repository/org/jruby/jruby-complete/9.1.13.0/jruby-complete-9.1.13.0.jar) to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of org.jruby.util.io.FilenoUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
LoadError: load error: jopenssl/load -- java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 1
              getStackTrace at java/lang/Thread.java:1654
           getBacktraceData at org/jruby/runtime/backtrace/TraceType.java:246
               getBacktrace at org/jruby/runtime/backtrace/TraceType.java:47
           prepareBacktrace at org/jruby/RubyException.java:235
                   preRaise at org/jruby/exceptions/RaiseException.java:216
                   preRaise at org/jruby/exceptions/RaiseException.java:183
                     <init> at org/jruby/exceptions/RaiseException.java:111
          newRaiseException at org/jruby/Ruby.java:4138
               newLoadError at org/jruby/Ruby.java:3988
  newLoadErrorFromThrowable at org/jruby/runtime/load/LoadService.java:924
  tryLoadingLibraryOrScript at org/jruby/runtime/load/LoadService.java:915
          smartLoadInternal at org/jruby/runtime/load/LoadService.java:531
                    require at org/jruby/runtime/load/LoadService.java:402
              requireCommon at org/jruby/RubyKernel.java:962
                  require19 at org/jruby/RubyKernel.java:955
                       call at org/jruby/RubyKernel$INVOKER$s$1$0$require19.gen:-1
                       call at org/jruby/internal/runtime/methods/JavaMethod.java:384
                       call at org/jruby/internal/runtime/methods/AliasMethod.java:61
                       call at org/jruby/runtime/callsite/CachingCallSite.java:161
                processCall at org/jruby/ir/interpreter/InterpreterEngine.java:314
                  interpret at org/jruby/ir/interpreter/StartupInterpreterEngine.java:73
                  interpret at org/jruby/ir/interpreter/InterpreterEngine.java:83
           INTERPRET_METHOD at org/jruby/internal/runtime/methods/MixedModeIRMethod.java:179
                    require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:59
                       call at org/jruby/internal/runtime/methods/MixedModeIRMethod.java:165
                       call at org/jruby/internal/runtime/methods/DynamicMethod.java:200
               cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:338
                       call at org/jruby/runtime/callsite/CachingCallSite.java:163
                processCall at org/jruby/ir/interpreter/InterpreterEngine.java:314
                  interpret at org/jruby/ir/interpreter/StartupInterpreterEngine.java:73
             INTERPRET_ROOT at org/jruby/ir/interpreter/Interpreter.java:112
                     <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/openssl.rb:1
                    execute at org/jruby/ir/interpreter/Interpreter.java:99
                    execute at org/jruby/ir/interpreter/Interpreter.java:35
                    execute at org/jruby/ir/IRTranslator.java:42
             runInterpreter at org/jruby/Ruby.java:840
                   loadFile at org/jruby/Ruby.java:2877
                       load at org/jruby/runtime/load/LibrarySearcher.java:243
                       load at org/jruby/runtime/load/LibrarySearcher.java:34
  tryLoadingLibraryOrScript at org/jruby/runtime/load/LoadService.java:891
          smartLoadInternal at org/jruby/runtime/load/LoadService.java:531
                    require at org/jruby/runtime/load/LoadService.java:402
              requireCommon at org/jruby/RubyKernel.java:962
                  require19 at org/jruby/RubyKernel.java:955
                       call at org/jruby/RubyKernel$INVOKER$s$1$0$require19.gen:-1
                       call at org/jruby/internal/runtime/methods/JavaMethod.java:384
                       call at org/jruby/internal/runtime/methods/AliasMethod.java:61
                       call at org/jruby/runtime/callsite/CachingCallSite.java:161
                processCall at org/jruby/ir/interpreter/InterpreterEngine.java:314
                  interpret at org/jruby/ir/interpreter/StartupInterpreterEngine.java:73
                  interpret at org/jruby/ir/interpreter/InterpreterEngine.java:83
           INTERPRET_METHOD at org/jruby/internal/runtime/methods/MixedModeIRMethod.java:179
                     (root) at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
                       call at org/jruby/internal/runtime/methods/MixedModeIRMethod.java:165
                       call at org/jruby/internal/runtime/methods/DynamicMethod.java:200
                    finvoke at org/jruby/RubyClass.java:908
                     invoke at org/jruby/runtime/Helpers.java:402
                 callMethod at org/jruby/RubyBasicObject.java:363
                       init at org/jruby/Ruby.java:1253
                newInstance at org/jruby/Ruby.java:339
                internalRun at org/jruby/Main.java:271
                        run at org/jruby/Main.java:232
                       main at org/jruby/Main.java:204
```

**Comment by sormuras** [comment]
Also running into this problem when building the documentation for **JUnit 5** on JDK-9 using `asciidoctor:asciidoctorj` with `'org.jruby:jruby-complete:9.1.13.0'`.

**Comment by sormuras** [comment]
Update: the error only occurs, when the **pdf** backend renderer is active. `html5` works fine in JDK-9.

**Comment by alejosolo** [comment]
- [ ]

**Comment by headius** [comment]
This has been fixed in jruby/jruby-openssl@f86bc0bc8dfdcb159570d96c82c434772e0ec619. It will be included in JRuby 9.1.14.

**Comment by sormuras** [comment]
We are still seeing this issue with 9.1.14 and the PDF backend of AsciiDoctorJ on Linux: https://junit.ci.cloudbees.com/blue/organizations/jenkins/JUnit5/detail/master/100/pipeline

**Comment by mkristian** [comment]
@sormuras any chance you give a few lines on how to trigger this broken pipeline locally ?

**Comment by sormuras** [comment]
1. Clone https://github.com/junit-team/junit5.git 
2. Enable PDF backend in `documentation/documentation.gradle`, around [line 84](https://github.com/junit-team/junit5/blob/master/documentation/documentation.gradle#L84).
3. Invoke `./gradlew --no-daemon --stacktrace asciidoctor`

**Comment by sormuras** [comment]
The log shows:
```
./gradlew --no-daemon --stacktrace asciidoctor
[...]
:documentation:asciidoctor
Download https://jcenter.bintray.com/org/asciidoctor/asciidoctorj-groovy-dsl/1.0.0.preview2/asciidoctorj-groovy-dsl-1.0.0.preview2.pom
Download https://repo1.maven.org/maven2/org/jruby/jruby-complete/1.7.26/jruby-complete-1.7.26.pom
Download https://repo1.maven.org/maven2/org/jruby/jruby-artifacts/1.7.26/jruby-artifacts-1.7.26.pom
Download https://repo1.maven.org/maven2/org/jruby/jruby-parent/1.7.26/jruby-parent-1.7.26.pom
Download https://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/1.8.9/groovy-all-1.8.9.pom
Download https://repo1.maven.org/maven2/org/jruby/jruby-complete/1.7.26/jruby-complete-1.7.26.jar
Download https://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/1.8.9/groovy-all-1.8.9.jar
Download https://jcenter.bintray.com/org/asciidoctor/asciidoctorj-groovy-dsl/1.0.0.preview2/asciidoctorj-groovy-dsl-1.0.0.preview2.jar
:documentation:asciidoctor FAILED
[...]
Caused by: org.jruby.exceptions.RaiseException: (LoadError) load error: jopenssl/load -- java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 1
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
	at RUBY.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:59)
	at RUBY.<main>(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/openssl.rb:1)
[...]
```
Mh, maybe the build still uses the `jruby-complete-1.7.26.jar` instead of the one configured in the `buildscript` dependency `classpath('org.jruby:jruby-complete:9.1.14.0')`...

Is there debug switch I can set on start up to emit the jruby version?

**Comment by mkristian** [comment]
but a look at the `gradle dependencies` should show where and how this `jruby-complete-1.7.26.jar` is used. I try to find some time later today and have look myself.

**Comment by sormuras** [comment]
A bit late, but here are the `gradle dependencies` from https://github.com/junit-team/junit5/blob/master/documentation/documentation.gradle

```
asciidoctor
+--- org.asciidoctor:asciidoctorj:1.5.6
|    +--- org.jruby:jruby-complete:1.7.26
|    \--- com.beust:jcommander:1.35
\--- org.asciidoctor:asciidoctorj-groovy-dsl:1.0.0.Alpha2
     +--- org.codehaus.groovy:groovy-all:2.3.9
     \--- org.asciidoctor:asciidoctorj:1.5.2 -> 1.5.6 (*)
```

**Comment by mkristian** [comment]
@sormuras there is clearly a `org.jruby:jruby-complete:1.7.26` on the classpath/classloader, eliminating this will resolve the overall problem.

**Comment by sormuras** [comment]
Aye. But I thought we override via:

```
buildscript {
	dependencies {
		// upgrade to latest jruby version due to a bugfix needed for Windows 10.
		// can be removed, when asciidoctorj uses this as a default version.
		classpath('org.jruby:jruby-complete:9.1.15.0')

		// classpath('org.asciidoctor:asciidoctorj-epub3:1.5.0-alpha.16')
		classpath('org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.16')
		classpath('org.asciidoctor:asciidoctorj-diagram:1.5.4.1')
	}
}

plugins {
	id 'org.asciidoctor.convert' version '1.5.7'
}

// ...

asciidoctorj {
	version = '1.5.6'
}

// ...
```
https://github.com/junit-team/junit5/blob/master/documentation/documentation.gradle

Not?

**Comment by mkristian** [comment]
@sormuras your gradle config needs a little patch for asciidoctor picking the right jruby version:
```diff
diff --git a/documentation/documentation.gradle b/documentation/documentation.gradle
index 1cf2676532..8698d2531d 100644
--- a/documentation/documentation.gradle
+++ b/documentation/documentation.gradle
@@ -2,7 +2,6 @@ buildscript {
        dependencies {
                // upgrade to latest jruby version due to a bugfix needed for Windows 10.
                // can be removed, when asciidoctorj uses this as a default version.
-               classpath('org.jruby:jruby-complete:9.1.15.0')

                // classpath('org.asciidoctor:asciidoctorj-epub3:1.5.0-alpha.16')
                classpath('org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.16')
@@ -35,6 +34,7 @@ test {
 */

 dependencies {
+       asciidoctor('org.jruby:jruby-complete:9.1.15.0')
        testImplementation(project(':junit-jupiter-api'))
        testImplementation(project(path: ':junit-jupiter-params', configuration: 'shadow'))
        testImplementation(project(':junit-platform-runner'))
```

**Comment by sormuras** [comment]
Will give it shot. Thanks for the hint.

**Comment by sormuras** [comment]
Without the `buildscript` line, the build fails to start on Windows 10.

When adding the `dependencies` entry, I get:
```
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant PKCS1_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant SSLV23_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant NO_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant PKCS1_OAEP_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant NAMED_CURVE
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant PKCS1_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant SSLV23_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant NO_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant PKCS1_OAEP_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant NAMED_CURVE
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant PKCS1_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant SSLV23_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant NO_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant PKCS1_OAEP_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant NAMED_CURVE
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant PKCS1_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant SSLV23_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant NO_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant PKCS1_OAEP_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant NAMED_CURVE
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant PKCS1_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant SSLV23_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant NO_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant PKCS1_OAEP_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant NAMED_CURVE
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant PKCS1_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant SSLV23_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant NO_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant PKCS1_OAEP_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant NAMED_CURVE
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant PKCS1_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant SSLV23_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant NO_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant PKCS1_OAEP_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant NAMED_CURVE
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant PKCS1_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant SSLV23_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant NO_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant PKCS1_OAEP_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant NAMED_CURVE
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant PKCS1_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant SSLV23_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant NO_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant PKCS1_OAEP_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant NAMED_CURVE
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant PKCS1_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant SSLV23_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant NO_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant PKCS1_OAEP_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant NAMED_CURVE
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant PKCS1_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant SSLV23_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant NO_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant PKCS1_OAEP_PADDING
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:26: warning: already initialized constant NAMED_CURVE
:documentation:asciidoctor FAILED
```

**Comment by sormuras** [comment]
This still only happens when the `pdf` backend is enabled.

**Comment by sormuras** [comment]
The relevant dependency tree now looks like:

```
asciidoctor
+--- org.jruby:jruby-complete:9.1.15.0
+--- org.asciidoctor:asciidoctorj:1.5.6
|    +--- org.jruby:jruby-complete:1.7.26 -> 9.1.15.0
|    \--- com.beust:jcommander:1.35
\--- org.asciidoctor:asciidoctorj-groovy-dsl:1.0.0.Alpha2
     +--- org.codehaus.groovy:groovy-all:2.3.9
     \--- org.asciidoctor:asciidoctorj:1.5.2 -> 1.5.6 (*)
```
