### ISSUE TITLE
A regexp with \K doesn't work in JRuby

### ISSUE THREAD

**Issue by thallgren** [jruby/jruby#4871]
### Environment
jruby-9.1.7.0 running on Linux 4.13.13-100.fc25.x86_64 #<nbsp>1 SMP Wed Nov 15 17:33:19 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Expected Behavior
The text matched by the part of the regex to the left of the \K is omitted from the overall regex match. Other than that the regex is matched normally from left to right.
```
$ irb
2.3.1 :001 > 'street'.match( /s\Kt/)
 => #<MatchData "t"> 
```
### Actual Behavior
\K does not match anything when using JRuby.
```
$ irb
jruby-9.1.7.0 :001 > 'street'.match( /s\Kt/)
 => nil 
```

**Comment by headius** [comment]
Huh, I'm not familiar with `\K`. Another bit we need to get into Joni.

**Comment by thallgren** [comment]
@headius, I must admin, I had never encountered \K either. I found this problem (and the one regarding \X) by testing diffs between Java and Ruby on [Regular-Expressions.info](https://www.regular-expressions.info/refflavors.html). Most headings in that TOC links to a page where the compared flavors can be selected at the top. I found it to be quite helpful.

**Comment by lopex** [comment]
Done in https://github.com/jruby/joni/commit/59dbb27ca0ab4b9617576286e3a1fd706e2a84f1

**Comment by thallgren** [comment]
AFAICT, this isn't completely fixed. When running my example I get a warning `Unknown escape \K is ignored`. I'm using joni-2.1.27 and the subsequent match fails.
```
unknownEscWarn:145, ScanEnvironment (org.joni)
convertBackslashValue:129, ScanEnvironment (org.joni)
fetchEscapedValueBackSlash:184, Lexer (org.joni)
fetchEscapedValue:179, Lexer (org.joni)
fetchToken:1166, Lexer (org.joni)
parseStringLoop:1090, Parser (org.joni)
parseExpTkByte:1085, Parser (org.joni)
parseExp:801, Parser (org.joni)
parseBranch:1342, Parser (org.joni)
parseSubExp:1368, Parser (org.joni)
parseRegexp:1401, Parser (org.joni)
compile:78, Analyser (org.joni)
<init>:155, Regex (org.joni)
<init>:134, Regex (org.joni)
<init>:120, Regex (org.joni)
<init>:100, Regex (org.joni)
```

**Comment by lopex** [comment]
There was indeed a break missing for \K in the lexer. Fixed in https://github.com/jruby/joni/commit/ee4bafb11106671b4f07838a016014078cca6c91

**Comment by lopex** [comment]
joni-2.1.28 is released

**Comment by thallgren** [comment]
Thanks. Works like a charm!

**Comment by lopex** [comment]
@thallgren, can you show the case that was not matching (or a reduced form of it), se we can plug it into our test suite ?
For now, we're running all of Onigmo's suite for \K at https://github.com/jruby/joni/blob/master/test/org/joni/test/TestU8.java#L102

**Comment by thallgren** [comment]
My test is for an evaluator for the Puppet type system, written in Java. It has its own `Regexp` and `Matcher` classes to wrap the Onigmo ones so the test will need to be rewritten to suit your style. This is the test that failed: https://github.com/puppetlabs/pcore-java/blob/b234d044d41b3db73aefa478c7ede779b073d27f/src/test/java/com/puppet/pcore/regex/RegexpTest.java#L189
