### ISSUE TITLE
Compiled module descriptor in complete JAR distro

### ISSUE THREAD

**Issue by sormuras** [jruby/jruby#4899]
Just loaded `jruby-complete-9.1.15.0.jar` from http://jruby.org/download and put it as a single JAR on the JPMS module path. Here it reports as a module with name:

- `com.headius.invokebinder`

There's a `module-info.class` in the root of the JAR. I guess this happens when merging dependencies into the _complete_ distro.

"complete" or "all" distro jars should not land on the module path -- but if they do, they should not present themselves as an explicit module nor provide an `Automatic-Module-Name` in the MANIFEST.

`jruby-complete-9.1.14.0.jar` is affected too.

`jar --describe-module` reports:
```
com.headius.invokebinder jar:file:///[...]/jruby-complete-9.1.15.0.jar/!module-info.class
exports com.headius.invokebinder
requires java.base
requires java.logging
```

**Comment by mkristian** [comment]
right we have to more careful what we include in our uber-jars, dito for the manifest.

**Comment by headius** [comment]
@mkristian There may be a cleaner way, but I believe I've addressed this in 83271e2.

**Comment by mkristian** [comment]
@headius that is good enough as starter - need to find a way to filter them out of all artifacts not only one. maybe wildcards work.

**Comment by busbey** [comment]
this is still an issue on 9.1.17.0. y'all want a new issue?

```
busbey$ /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/bin/jar --describe-module -f ~/.m2/repository/org/jruby/jruby-complete/9.1.17.0/jruby-complete-9.1.17.0.jar
com.headius.invokebinder jar:file:///Users/busbey/.m2/repository/org/jruby/jruby-complete/9.1.17.0/jruby-complete-9.1.17.0.jar/!module-info.class
exports com.headius.invokebinder
requires java.base
requires java.logging
```

Found it because the Maven Enforcer Plugin got angry when the Apache HBase project tried to upgrade from 9.1.10.0 to 9.1.17.0

```
[INFO] Restricted to JDK 1.8 yet org.jruby:jruby-complete:jar:9.1.17.0:compile contains module-info.class targeted to JDK 1.9
[WARNING] Rule 4: org.apache.maven.plugins.enforcer.EnforceBytecodeVersion failed with message:
HBase has unsupported dependencies.
  HBase requires that all dependencies be compiled with version 1.8 or earlier
  of the JDK to properly build from source.  You appear to be using a newer dependency. You can use
  either "mvn -version" or "mvn enforcer:display-info" to verify what version is active.
  Non-release builds can temporarily build with a newer JDK version by setting the
  'compileSource' property (eg. mvn -DcompileSource=1.8 clean package).
Found Banned Dependency: org.jruby:jruby-complete:jar:9.1.17.0
Use 'mvn dependency:tree' to locate the source of the banned dependencies.
```
