### ISSUE TITLE
NameError: uninitialized constant Fiddle::CParser::TYPE_SIZE_T

### ISSUE THREAD

**Issue by ankane** [jruby/jruby#5955]
Hi, I'm running  into an error with `fiddle` with the latest JRuby on MacOS 10.14.6 (may affect other platforms as well).

### Environment

- jruby 9.2.8.0 (2.5.3) 2019-08-12 a1ac7ff Java HotSpot(TM) 64-Bit Server VM 25.192-b12 on 1.8.0_192-b12 +jit [darwin-x86_64]

### Expected Behavior

No error when `size_t` is used. Here's a simple script to reproduce:

```ruby
require "fiddle/import"

module Hello
  extend Fiddle::Importer
  dlload "libc.dylib" # change extension on other platforms
  extern "size_t puts(char* str)"
end
```

(this is not the actual interface for `puts` but works for demonstration)

### Actual Behavior

Raises

```txt
NameError: uninitialized constant Fiddle::CParser::TYPE_SIZE_T
Did you mean?  Fiddle::TYPE_INT
    const_missing at org/jruby/RubyModule.java:3746
      parse_ctype at /Users/andrew/.rbenv/versions/jruby-9.2.8.0/lib/ruby/stdlib/fiddle/cparser.rb:164
  parse_signature at /Users/andrew/.rbenv/versions/jruby-9.2.8.0/lib/ruby/stdlib/fiddle/cparser.rb:92
           extern at /Users/andrew/.rbenv/versions/jruby-9.2.8.0/lib/ruby/stdlib/fiddle/import.rb:166
    <class:Hello> at repro.rb:6
           <main> at repro.rb:3
```

**Comment by ahorek** [comment]
hi @ankane !
do you have a real world example that you would like to support on jruby?

**Comment by ankane** [comment]
Hey @ahorek, thanks for the response! I've created a `fiddle` branch in a number of projects to see if it was possible to switch from FFI. Here are a few that are affected by this issue.

- [Vowpal Wabbit](https://github.com/ankane/vowpalwabbit/tree/fiddle)
- [NGT](https://github.com/ankane/ngt/tree/fiddle)

And a few that are affected by #5956.

- [LightGBM](https://github.com/ankane/lightgbm/tree/fiddle)
- [xLearn](https://github.com/ankane/xlearn/tree/fiddle)

**Comment by ankane** [comment]
Also, seeing errors with `malloc`.

```ruby
require "fiddle"

Fiddle::Pointer.malloc(100)
```

Throws

```txt
NameError: uninitialized constant Fiddle::Pointer::LibC
  const_missing at org/jruby/RubyModule.java:3746
         malloc at /Users/andrew/.rbenv/versions/jruby-9.2.8.0/lib/ruby/stdlib/fiddle/jruby.rb:168
         <main> at malloc.rb:3
```

**Comment by ahorek** [comment]
Also, seeing errors with malloc. - yeah, that one will be fixed by https://github.com/jruby/ruby/pull/2

**Comment by ankane** [comment]
Awesome, thanks!

**Comment by ahorek** [comment]
ok, there are 2 more failures

```
DatasetTest#test_weight:
NoMethodError: undefined method `[]=' for #<Fiddle::Pointer:0x13cc0b90>
Did you mean?  []
    /lightgbm/lib/lightgbm/ffi.rb:172:in `write_array'
    /lightgbm/lib/lightgbm/ffi.rb:121:in `write_array_of_float'
    /lightgbm/lib/lightgbm/dataset.rb:43:in `initialize'
    /lightgbm/test/dataset_test.rb:21:in `test_weight'
```

```
DatasetTest#test_data_string:
TypeError: cannot convert parameter to native pointer
    /lightgbm/lib/lightgbm/ffi.rb:24:in `LGBM_DatasetCreateFromFile'
    /lightgbm/lib/lightgbm/dataset.rb:23:in `initialize'
    /lightgbm/test/dataset_test.rb:5:in `test_data_string'
```

I think I can fix the first one, but the second one will be more tricky

**Comment by ankane** [comment]
For 2, is that due to string -> pointer conversion?

**Comment by ahorek** [comment]
string -> pointer conversion is fixed https://github.com/jruby/jruby/pull/5960 , but there're still issues https://github.com/jruby/jruby/issues/6034

**Comment by headius** [comment]
Anything left here or can we call this one fixed?

**Comment by ahorek** [comment]
there's still work in order to fully support those gems, but the original issue is fixed.

**Comment by headius** [comment]
@ahorek I prefer individual issues for individual problems, so we'll call this fixed and move on to others.

**Comment by headius** [comment]
@ankane @ahorek Please file additional unique issues for anything else that's still broken. Doesn't have to be an issue-per-failure or anything that fine-grained, but something better than "these half dozen gems don't work". Thank you!

**Comment by ankane** [comment]
Thanks @headius! Will test out the changes when the next version of JRuby is out (unless there's an easy way to get JRuby head with rbenv, but didn't see it in the list).

**Comment by headius** [comment]
@ankane I know rvm supports `jruby-head` but not sure about rbenv. If you want to just download a tarball, we push snapshot builds of that to Maven here: https://oss.sonatype.org/content/repositories/snapshots/org/jruby/jruby-dist/

Just put the `bin` dir in `PATH` and you're up and running.
