### ISSUE TITLE
NullPointerException or "class is not compiled Ruby" error when using a "for" loop

### ISSUE THREAD

**Issue by rsim** [jruby/jruby#6184]
### Environment
First appeared in
* jruby 9.2.8.0 (2.5.3) 2019-08-12 a1ac7ff Java HotSpot(TM) 64-Bit Server VM 25.191-b12 on 1.8.0_191-b12 +jit [darwin-x86_64]

Can be reproduced with a different error message in the latest
* jruby 9.2.11.1 (2.5.7) 2020-03-25 b1f55b1a40 Java HotSpot(TM) 64-Bit Server VM 25.191-b12 on 1.8.0_191-b12 +jit [darwin-x86_64]

### Expected Behavior

Create a file `test.rb` with a content
```ruby
for i in [1, 2]
  puts i
end
```

And compile it and try to load:
```
jrubyc test.rb
jruby -e "load 'test.class'"
```

When using JRuby 9.2.7.0 then there are no error messages and expected results are shown.

### Actual Behavior

When using JRuby 9.2.8.0 it fails:
```
$ jrubyc test.rb
$ jruby -e "load 'test.class'"
LoadError: test.class is not compiled Ruby; use java_import to load normal classes
    load at org/jruby/RubyKernel.java:1022
  <main> at -e:1
```

When using JRuby 9.2.11.1 it fails with more detailed stack trace:
```
$ jrubyc test.rb
$ jruby -e "load 'test.class'"
Unhandled Java exception: java.lang.NullPointerException
java.lang.NullPointerException: null
                   getLocalVariable at org/jruby/ir/IRClosure.java:290
                             decode at org/jruby/ir/operands/LocalVariable.java:129
                             decode at org/jruby/ir/persistence/IRReaderStream.java:493
                      decodeOperand at org/jruby/ir/persistence/IRReaderStream.java:371
                     decodeVariable at org/jruby/ir/persistence/IRReaderStream.java:380
                             decode at org/jruby/ir/instructions/ReceivePreReqdArgInstr.java:38
                        decodeInstr at org/jruby/ir/persistence/IRReaderStream.java:318
               decodeInstructionsAt at org/jruby/ir/persistence/IRReaderStream.java:218
                      lambda$load$0 at org/jruby/ir/persistence/IRReader.java:47
                          getEngine at org/jruby/ir/interpreter/InterpreterContext.java:74
                    getInstructions at org/jruby/ir/interpreter/InterpreterContext.java:85
  computeScopeFlagsFromInstructions at org/jruby/ir/interpreter/InterpreterContext.java:189
                  computeScopeFlags at org/jruby/ir/IRScope.java:750
         calculateClosureScopeFlags at org/jruby/ir/IRScope.java:680
                  computeScopeFlags at org/jruby/ir/IRScope.java:753
                          getEngine at org/jruby/ir/interpreter/InterpreterContext.java:75
                     INTERPRET_ROOT at org/jruby/ir/interpreter/Interpreter.java:96
                            execute at org/jruby/ir/interpreter/Interpreter.java:81
                            execute at org/jruby/ir/interpreter/Interpreter.java:30
                            execute at org/jruby/ir/IRTranslator.java:42
                     runInterpreter at org/jruby/Ruby.java:1218
                          loadScope at org/jruby/Ruby.java:2799
                               load at org/jruby/runtime/load/LibrarySearcher.java:259
                               load at org/jruby/runtime/load/LoadService.java:343
                         loadCommon at org/jruby/RubyKernel.java:1039
                               load at org/jruby/RubyKernel.java:1009
                               call at org/jruby/RubyKernel$INVOKER$s$load.gen:-1
                               call at org/jruby/internal/runtime/methods/JavaMethod.java:417
                       cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:375
                               call at org/jruby/runtime/callsite/CachingCallSite.java:174
                  invokeOther0:load at -e:1
                             <main> at -e:1
                invokeWithArguments at java/lang/invoke/MethodHandle.java:627
                               load at org/jruby/ir/Compiler.java:89
                          runScript at org/jruby/Ruby.java:1205
                        runNormally at org/jruby/Ruby.java:1128
                        runNormally at org/jruby/Ruby.java:1146
                        runFromMain at org/jruby/Ruby.java:958
                      doRunFromMain at org/jruby/Main.java:412
                        internalRun at org/jruby/Main.java:304
                                run at org/jruby/Main.java:234
                               main at org/jruby/Main.java:206
```

As a workaround, we could replace `for` loops with `each` loops in our code to avoid this compilation problem.

This is similar to #5740 which was identified in JRuby 9.2.7.0.

**Comment by enebo** [comment]
We merged a branch this winter which will be in 9.3.0.0 which will fix this (ironically for loops have regressed again on master but we knew it at the time).  Our test coverage has improved quite a bit so we are hoping to make it past having these occasional problems.  Targetting for 9.3 since it is a nice marker (since for is currently broken on HEAD atm).

**Comment by headius** [comment]
This does still fail on 9.3. Seems like we're missing some decoding logic for this for loop?

```
$ jruby -e 'load "./test.class"'
Unhandled Java exception: java.lang.NullPointerException
java.lang.NullPointerException: null
                   getLocalVariable at org/jruby/ir/IRClosure.java:283
                             decode at org/jruby/ir/operands/LocalVariable.java:129
                             decode at org/jruby/ir/persistence/IRReaderStream.java:506
                      decodeOperand at org/jruby/ir/persistence/IRReaderStream.java:384
                     decodeVariable at org/jruby/ir/persistence/IRReaderStream.java:393
                             decode at org/jruby/ir/instructions/ReceivePreReqdArgInstr.java:38
                        decodeInstr at org/jruby/ir/persistence/IRReaderStream.java:331
               decodeInstructionsAt at org/jruby/ir/persistence/IRReaderStream.java:231
                      lambda$load$0 at org/jruby/ir/persistence/IRReader.java:48
                          getEngine at org/jruby/ir/interpreter/InterpreterContext.java:74
```

**Comment by enebo** [comment]
Written for posterity so it does not look like a dangling question.  All for loops are broken after we merged the work we did in removing IRScope from runtime.  This was a known issue that will get fixed for 9.3.  Ultimately the issue is that IRFor increments depth of all lvars and our loading code is not doing that.

**Comment by JesseChavez** [comment]
I had a similar issue but I was not getting:
```
Unhandled Java exception: java.lang.NullPointerException
java.lang.NullPointerException: null
```
Instead I was getting as below because my code was running in a thread.
```
org.jruby.runtime.scopes.DynamicScope7.setValueVoid(Unknown Source)
org.jruby.runtime.scopes.DynamicScope0.setValueVoid(Unknown Source)
org.jruby.ir.interpreter.InterpreterEngine.setResult(InterpreterEngine.java:572)
org.jruby.ir.interpreter.InterpreterEngine.receiveArg(InterpreterEngine.java:273)
org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:68)
org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:116)
org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136)
org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:166)
org.jruby.runtime.BlockBody.yield(BlockBody.java:108)
org.jruby.runtime.Block.yield(Block.java:184)
org.jruby.RubyArray.each(RubyArray.java:1809)
org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:555)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:332)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:86)
org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:93)
org.jruby.ir.instructions.CallBase.interpret(CallBase.java:549)
org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)
org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86)
org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:156)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:143)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:375)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:174)
org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)
org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:80)
org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:121)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:108)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:354)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:143)
org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:345)
org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:80)
org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:121)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:108)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:354)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:143)
org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:345)
org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:116)
org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136)
org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:60)
org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:52)
org.jruby.runtime.Block.call(Block.java:139)
org.jruby.RubyProc.call(RubyProc.java:318)
org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105)
java.lang.Thread.run(Thread.java:748)
```
Using `each` loops fix the problem

**Comment by JesseChavez** [comment]
I could replicate the issue with the compiled version of:
```ruby
sample = Thread.new do
  for i in [1, 2]
    puts i
  end
end

sample.join
```
here is the stack trace:

```
java.lang.RuntimeException: org.jruby.runtime.scopes.DynamicScope1 only supports scopes with 1 variables
	at org.jruby.runtime.scopes.DynamicScope1.sizeError(Unknown Source)
	at org.jruby.runtime.scopes.DynamicScope1.setValueVoid(Unknown Source)
	at org.jruby.runtime.scopes.DynamicScope1.setValueVoid(Unknown Source)
	at org.jruby.runtime.scopes.DynamicScope0.setValueVoid(Unknown Source)
	at org.jruby.ir.interpreter.InterpreterEngine.setResult(InterpreterEngine.java:572)
	at org.jruby.ir.interpreter.InterpreterEngine.receiveArg(InterpreterEngine.java:273)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:68)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:116)
	at org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136)
	at org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:166)
	at org.jruby.runtime.BlockBody.yield(BlockBody.java:108)
	at org.jruby.runtime.Block.yield(Block.java:184)
	at org.jruby.RubyArray.each(RubyArray.java:1809)
	at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:555)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:332)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:86)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:93)
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:549)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:116)
	at org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:136)
	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:60)
	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:52)
	at org.jruby.runtime.Block.call(Block.java:139)
	at org.jruby.RubyProc.call(RubyProc.java:318)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105)
	at java.lang.Thread.run(Thread.java:748)
Unhandled Java exception: java.lang.RuntimeException: org.jruby.runtime.scopes.DynamicScope1 only supports scopes with 1 variables
java.lang.RuntimeException: org.jruby.runtime.scopes.DynamicScope1 only supports scopes with 1 variables
        sizeError at org/jruby/runtime/scopes/DynamicScope1:-1
     setValueVoid at org/jruby/runtime/scopes/DynamicScope1:5
     setValueVoid at org/jruby/runtime/scopes/DynamicScope1:5
     setValueVoid at org/jruby/runtime/scopes/DynamicScope0:5
        setResult at org/jruby/ir/interpreter/InterpreterEngine.java:572
       receiveArg at org/jruby/ir/interpreter/InterpreterEngine.java:273
        interpret at org/jruby/ir/interpreter/StartupInterpreterEngine.java:68
  INTERPRET_BLOCK at org/jruby/ir/interpreter/Interpreter.java:116
  commonYieldPath at org/jruby/runtime/MixedModeIRBlockBody.java:136
          doYield at org/jruby/runtime/IRBlockBody.java:166
            yield at org/jruby/runtime/BlockBody.java:108
            yield at org/jruby/runtime/Block.java:184
             each at org/jruby/RubyArray.java:1809
             call at org/jruby/RubyArray$INVOKER$i$0$0$each.gen:-1
             call at org/jruby/internal/runtime/methods/JavaMethod.java:555
     cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:332
             call at org/jruby/runtime/callsite/CachingCallSite.java:86
         callIter at org/jruby/runtime/callsite/CachingCallSite.java:93
        interpret at org/jruby/ir/instructions/CallBase.java:549
      processCall at org/jruby/ir/interpreter/InterpreterEngine.java:361
        interpret at org/jruby/ir/interpreter/StartupInterpreterEngine.java:72
  INTERPRET_BLOCK at org/jruby/ir/interpreter/Interpreter.java:116
  commonYieldPath at org/jruby/runtime/MixedModeIRBlockBody.java:136
             call at org/jruby/runtime/IRBlockBody.java:60
             call at org/jruby/runtime/IRBlockBody.java:52
             call at org/jruby/runtime/Block.java:139
             call at org/jruby/RubyProc.java:318
              run at org/jruby/internal/runtime/RubyRunnable.java:105
              run at java/lang/Thread.java:748
```

**Comment by enebo** [comment]
@JesseChavez both of these errors are outcomes of the same base issue.  Our internal representation adds an extra IRScope (IRFor) for 'for' loops and this in turn changes all depth counts for any variables contained in for loops (and any blocks in those for loops etc...).  Being off by one (or more if nested fors) will either hit a scope with not enough variables and give your error or access a scope with enough variables but no set value (and cause an NPE).

**Comment by JesseChavez** [comment]
Oh I see, thanks for the information @enebo

**Comment by jsvd** [comment]
I believe we're seeing something similar in Logstash, with or without indy enabled:

<details>
  <summary>Click to expand</summary>

```
Exception in thread "Ruby-0-Thread-58: /private/tmp/logstash-7.5.2/logstash-core/lib/logstash/pipeline_action/reload.rb:48" java.lang.RuntimeException: org.jruby.runtime.scopes.DynamicScope0 only supports scopes with 0 variables
	at org.jruby.runtime.scopes.DynamicScope0.sizeError(Unknown Source)
	at org.jruby.runtime.scopes.DynamicScope0.setValueVoid(Unknown Source)
	at org.jruby.ir.interpreter.InterpreterEngine.setResult(InterpreterEngine.java:576)
	at org.jruby.ir.interpreter.InterpreterEngine.receiveArg(InterpreterEngine.java:273)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:68)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:114)
	at org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:151)
	at org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:187)
	at org.jruby.runtime.BlockBody.yield(BlockBody.java:116)
	at org.jruby.runtime.Block.yield(Block.java:170)
	at org.jruby.RubyArray.selectCommon(RubyArray.java:2629)
	at org.jruby.RubyArray.select(RubyArray.java:2663)
	at org.jruby.RubyArray$INVOKER$i$0$0$select.call(RubyArray$INVOKER$i$0$0$select.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:555)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:332)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:86)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:93)
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:537)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:80)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:138)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:125)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
	at org.jruby.RubyClass.finvoke(RubyClass.java:548)
	at org.jruby.runtime.Helpers.invoke(Helpers.java:446)
	at org.jruby.RubyBasicObject.callMethod(RubyBasicObject.java:355)
	at org.logstash.execution.PipelineReporterExt.toHash(PipelineReporterExt.java:122)
	at org.logstash.execution.PipelineReporterExt.snapshot(PipelineReporterExt.java:97)
	at org.logstash.execution.PipelineReporterExt$INVOKER$i$0$0$snapshot.call(PipelineReporterExt$INVOKER$i$0$0$snapshot.gen)
	at org.jruby.RubyClass.finvoke(RubyClass.java:548)
	at org.jruby.runtime.Helpers.invoke(Helpers.java:446)
	at org.jruby.RubyBasicObject.callMethod(RubyBasicObject.java:355)
	at org.logstash.execution.ShutdownWatcherExt.pipelineReportSnapshot(ShutdownWatcherExt.java:89)
	at org.logstash.execution.ShutdownWatcherExt.start(ShutdownWatcherExt.java:151)
	at org.logstash.execution.ShutdownWatcherExt.lambda$start$0(ShutdownWatcherExt.java:48)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

**Comment by enebo** [comment]
@jsvd can you open that as a new issue?  That is a similar error but very unlikely to be related to for loops and IR persisted loading.  It looks more like a bug with a block getting compiled indepdendently of the method.  We have had this issue in the past and thought we fixed these.

**Comment by jsvd** [comment]
I can. I appended this here due to your comment where off by one errors would either cause a NPE or these scope errors, and when running logstash locally I can trigger 3 different errors, listed at the bottom of this gist: https://gist.github.com/jsvd/59ebbd675cb96036e3e8c064575db1eb#file-gistfile1-txt-L72-L389

**Comment by enebo** [comment]
@jsvd we get similar errors when we compile a closure and think it has eliminated its own scope but then we insert a scope in there anyways (accessing a zero var scope when we really want the variable from the parent).   Our fix has been to make sure the root parent and all children all resolve/compile at the same time but it appears something is not working in your case.

**Comment by jsvd** [comment]
@enebo I've created https://github.com/jruby/jruby/issues/6207

Unfortunately I haven't been able to produce a smaller replication script, as even running logstash can sometimes take several minutes to crash.
