### ISSUE TITLE
File.directory? returns false on macOS M1 for a directory

### ISSUE THREAD

**Issue by rykov** [jruby/jruby#6813]
**Environment Information**
  
* jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.12+0 on 11.0.12+0 +jit [darwin-aarch64]
* Darwin 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64

Also tested on:
* jruby 9.2.20.0-SNAPSHOT (2.5.8) 2021-09-02 a7e20fa6a6 OpenJDK 64-Bit Server VM 17+0 on 17+0 +jit [darwin-aarch64]

**Expected Behavior**

* `File.stat(directory).directory?` should return `true`
* Here's the correct functionality on Linux:

```
$ uname -mrsv
Linux 5.10.47-linuxkit #1 SMP PREEMPT Sat Jul 3 21:50:16 UTC 2021 aarch64
$ jruby -v
jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 16.0.2+7-67 on 16.0.2+7-67 +jit [linux-aarch64]
$ jruby -e 'puts File.stat(".").directory?'
true
```

**Actual Behavior**

* `File.stat(directory).directory?` returns `false`

```
$ uname -mrsv
Darwin 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64
$ jruby -v
jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.12+0 on 11.0.12+0 +jit [darwin-aarch64]
$ jruby -e 'puts File.stat(".").directory?'
false
```

**Comment by kovyrin** [comment]
Tested on my M5 and it seems to work:

```
kovyrin-elastic@elastic-m1 jruby-9.2.19.0 % uname -mrsv
Darwin 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64
kovyrin-elastic@elastic-m1 jruby-9.2.19.0 % bin/jruby -e 'puts File.stat(".").directory?'
true
```

**Comment by rykov** [comment]
@kovyrin I wonder if this has something to do with code signing and entitlements. How are you bypassing the JFFI code signature error? I ask because I was having the following error https://github.com/jnr/jnr-ffi/issues/257#issuecomment-915153246, and I solved it by ad-hoc signing the `jnilib`.

**Comment by rykov** [comment]
Upon further review, it seems that using the native POSIX/FFI library is what causes the incorrect behavior. Here's the behavior after the `codesign` hack described in https://github.com/jnr/jnr-ffi/issues/257#issuecomment-915153246:

```
$ jruby -Xnative.enabled=false -Xnative.verbose=true -e 'puts File.stat(".").directory?'
true
$ jruby -Xnative.enabled=true -Xnative.verbose=true -e 'puts File.stat(".").directory?'
Successfully loaded native POSIX impl.
false
```

@kovyrin In your particular case, I believe that native implementation silently fails, and jRuby falls back on the Java implementation. Here's what happens if I don't `codesign` the `.jnilib`:

```
$ jruby -e 'puts File.stat(".").directory?' # Correct answer, no errors
true

$ jruby -Xnative.verbose=true -e 'puts File.stat(".").directory?'
Failed to load native POSIX impl; falling back on Java impl. Stacktrace follows.
... snip "Trying to load an unsigned library" stacktrace ...
true
```

**Comment by kovyrin** [comment]
@rykov Yes, you're absolutely correct! It works for me because it fails to load the native implementation. With the codesign hack I can reproduce the issue as well.

**Comment by headius** [comment]
Sigh... ok so there's a bit more work to investigate on the M1 side of things.

We will probably not get this fixed in time for 9.3 but we can land something shortly thereafter in 9.3.1. I will try to review the code signing situation soon. Thanks for your patience, folks!

**Comment by headius** [comment]
It looks like this is working now that we have jffi loading properly! I confirmed on my M1 mac mini that native posix loads AND this returns true as expected.

**Comment by mgroebner** [comment]
Just installed JRuby 9.3.2.0 and still have the issue on my MacBook Pro - Apple M1 Pro.

```
uname -mrsv
Darwin 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64

./bin/jruby -v                                                                                             
jruby 9.3.2.0 (2.6.8) 2021-12-01 0b8223f905 OpenJDK 64-Bit Server VM 11.0.12+0 on 11.0.12+0 +jit [darwin-aarch64]

./bin/jruby -e 'puts File.stat(".").directory?'                                                               
false
```

**Comment by rykov** [comment]
@mgroebner based on @headius tweets (and your experience), it looks like the fix will be in 9.3.3.0.

**Comment by headius** [comment]
This was likely fixed by https://github.com/jnr/jnr-posix/pull/173 which will be in all upcoming JRuby releases.
