### ISSUE TITLE
Regression for non matching Regexp in `9.3.4`

### ISSUE THREAD

**Issue by andsel** [jruby/jruby#7484]
**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
```
jruby 9.3.4.0 (2.6.8) 2022-03-23 eff48c1ebf OpenJDK 64-Bit Server VM 11.0.15+10 on 11.0.15+10 +jit [x86_64-linux]
```
* Operating system and platform (e.g. `uname -a`)
```
Linux kalimera 5.15.0-53-generic #59~20.04.1-Ubuntu SMP Thu Oct 20 15:10:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Other relevant info you may wish to add:
~~* Installed or activated gems~~
~~* Application/framework version (e.g. Rails, Sinatra)~~
~~* Environment variables~~

**Expected Behavior**

* Non matching regexp with `Regexp::MULTILINE` shouldn't have performance regression between `9.2.20` and `9.3.4`

* Provide an executable Ruby script or a link to an example repository.
```ruby
require "securerandom"

puts ">>> Setup, using JRuby #{JRUBY_VERSION}"

regexp = Regexp.new("(?:.*)(Cannot|Failed) login (?<user>S+) (?:.*)", Regexp::MULTILINE)

puts ">>> Regexp instantiated and start processing"
start_time = Time.now

rand_str = SecureRandom.alphanumeric(5000)
msg = "foo bar blubb cannot login i123456 #{rand_str}"
#10000.times do
100.times do
  regexp.match(msg)
  #msg.match(/(?:.*)(Cannot|Failed) login (?<user>\S+) (?:.*)/)
end
stop_time = Time.now

execution_time = stop_time - start_time
puts ">>> Regexp terminated, executes in #{execution_time} sec"
```

**Actual Behavior**
The above script with JRuby `9.2.20.0` perform under the second:
```bash
$ ruby regexp_regression_reproducer.rb
>>> Setup, using JRuby 9.2.20.1
>>> Regexp instantiated and start processing
>>> Regexp terminated, executes in 0.217434 sec
```

with JRuby `9.3.4.0` performs in ~40 seconds:
```bash
$ ruby regexp_regression_reproducer.rb
>>> Setup, using JRuby 9.3.4.0
>>> Regexp instantiated and start processing
>>> Regexp terminated, executes in 38.519028 sec
```

but if I switch 
```ruby
regexp.match(msg)
```

to

```ruby
msg.match(/(?:.*)(Cannot|Failed) login (?<user>\S+) (?:.*)/)
```

it goes back to have good performance:
```bash
$ ruby regexp_regression_reproducer.rb
>>> Setup, using JRuby 9.3.4.0
>>> Regexp instantiated and start processing
>>> Regexp terminated, executes in 0.176172 sec
```
So I suspect is something related to the way the `Regexp` is instantiated, in particular the `Regexp::MULTILINE`.

**Comment by andsel** [comment]
With JRuby `9.4.0.0` the regression was fixed

```
andrea@kalimera: $ ruby reproducer.rb
>>> Setup, using JRuby 9.4.0.0
>>> Regexp instantiated and start processing
>>> Regexp terminated, executes in 0.049103 sec
```

**Comment by enebo** [comment]
@andsel unfortunately, this seems to be because our securerandom broke and it was always returing a string of all "A"s.  So the problem still exists.

**Comment by enebo** [comment]
The regression was identified and we are trying to figure out why it was made in the first place.  The code added when we changed things now passes with the code added back.

**Comment by andsel** [comment]
Hi @enebo thank's for replying. 
Do you have a PR or commit reference for these changes, maybe I can look into.

**Comment by enebo** [comment]
@andsel I will commit fix to both 9.3 and 9.4 this morning.  It is just re-enabling part of joni which was removed when a failing test was found (seems like it was losing track of multiple byte character and corrupting the search).  That test now passes.  Best guess is we fixed some encoding data in jcodings.

**Comment by jsvd** [comment]
@enebo I just tested the jruby-9.3 branch and the script still takes > 20s to complete.
The easiest way I can make the problem go away is to recompile jruby with joni 2.1.40.

```diff
diff --git a/core/pom.rb b/core/pom.rb
index fce61dbe3d..ad987e6703 100644
--- a/core/pom.rb
+++ b/core/pom.rb
@@ -51,7 +51,7 @@ project 'JRuby Base' do
   jar 'com.github.jnr:jffi:${jffi.version}'
   jar 'com.github.jnr:jffi:${jffi.version}:native'
 
-  jar 'org.jruby.joni:joni:2.1.45'
+  jar 'org.jruby.joni:joni:2.1.40'
```

**Comment by jsvd** [comment]
that said, the nightly jruby 9.4.1.0 daily snapshot does seem to solve it:

```
/tmp/jruby-head
❯ bin/jruby -v          
jruby 9.4.1.0-SNAPSHOT (3.1.0) 2023-01-18 030e5129ee OpenJDK 64-Bit Server VM 17.0.4.1+1 on 17.0.4.1+1 +jit [arm64-darwin]

/tmp/jruby-head
❯ bin/jruby script.rb
>>> Setup, using JRuby 9.4.1.0-SNAPSHOT
>>> Regexp instantiated and start processing
>>> Regexp terminated, executes in 0.03128 sec
```

**Comment by enebo** [comment]
@jsvd I am very confused by this but I see it is not fixed.  I am at a loss.  It probably is not fixed on 9.4 either unless the random number fixes have landed.

**Comment by enebo** [comment]
Yeah 9.4 is still broken too (random fixes landed so it is not matching on a huge string of all AAAAAAAAAAAAAAAAAAA).  Seeing it worked on 2.1.40 hopefully will save some time in bisecting.

**Comment by enebo** [comment]
I found the commit: 39d8c21144de747bb9e2ba0753818dbe2cf136eb.  I do not think reverting this will break any regexps and it definitely fixes the regression but I am asking the author for more info since the commit message does not really help to know the impact of reverting it.   This also looks like a commit which might just be missing an '=' too so it may just need to be tweaked.

**Comment by jsvd** [comment]
Many thanks @enebo, I see 2.1.46 is tagged and ready to go?

For context, we're having users drastically increasing their infrastructure spend to accommodate the performance regression until a new Logstash version is out with a JRuby that contains a fixed joni.

Do you want me to open an PR for JRuby to bump joni on the 9.4 and 9.3 branches?

**Comment by enebo** [comment]
@jsvd It would have been put onto HEAD for both versions on Friday but sonatype broke for me.  I have a support issue open today.  Once I can finish releasing the artifact I will update.

**Comment by enebo** [comment]
Since I did not mention this.  Upon talking we looked at onigmo source and realized there was a small mistake in the port that caused the regression.  I corrected this (which is what 2.1.46 contains).

**Comment by enebo** [comment]
@jsvd @andsel Please check out 80c7910ee5.  Kick those tires :t-rex:

**Comment by jsvd** [comment]
Looks good on my local tests! 🚢 it!

**Comment by kares** [comment]
would probably be worth contributing a regression guard unit test, if possible (CI won't be too slow) on the joni or jruby repo.

**Comment by enebo** [comment]
@kares yeah I guess what was submitted is ok but I wish I understood this enough to make something which would be instantaneous on one regexp fixed but heat death long if it was broken.  This regexp + 4000 char is already 100x slower but I suspect this could be 10,000x slower if I traced through onimo.
